name: contributions-getter-actions
description: 'get all of the repositories you contributed to since your account\'s creation'
inputs:
    token:
      description: 'Your GitHub token'
      required: true
    output-file-name:
      description: 'The name of the file in which to output the contributions'
      required: false
      default: 'README.md'
    header-format:
      description: 'Check documentation'
      required: false
    highlight-format:
      description: 'Check documentation'
      required: false
    file-before-path:
      description: 'Check documentation'
      required: false
    minimum-stars-for-highlight:
      description: 'Check documentation'
      required: false
      type: number
    months-interval:
      description: 'Check documentation'
      required: false
      type: number
runs:
  using: composite
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        path: 'target'
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Install npm packages and build code
      run: cd "${{ github.action_path }}" && npm install && npm run build
    - name: Set env vars
      run: |
        for i in "${{ inputs.header-format }}" "${{ inputs.highlight-format }}" "${{ inputs.file-before-path }}" "${{ inputs.minimum-stars-for-highlight }}" "${{ inputs.months-interval }}"; do
          if [ -n "$i" ]; then
            echo "$i" >> $GITHUB_ENV
          fi
    - name: Run
      run: cd "${{ github.action_path }}" && npm start --silent > "$GITHUB_WORKSPACE/target/${{ inputs.output-file-name }}"
      shell: bash
    - name: Commit
      run: |
        cd "$GITHUB_WORKSPACE/target
        git add -A
        git commit -m "Update contributions" --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        git push
