name: contributions-getter-actions
description: "Update a markdown file with all of the repositories you have contributed to since your account creation"
inputs:
  token:
    description: "Your GitHub token"
    required: true
  username:
    description: "Your GitHub username"
    required: false
    default: ${{ github.repository_owner }}
  output-file-path:
    description: "The name of the file in which to output the contributions"
    required: false
    default: "README.md"
  header-format:
    description: "Check documentation"
    required: false
  highlight-format:
    description: "Check documentation"
    required: false
  file-before-path:
    description: "Check documentation"
    required: false
  file-after-path:
    description: "Check documentation"
    required: false
  minimum-stars-for-highlight:
    description: "Check documentation"
    required: false
  months-interval:
    description: "Check documentation"
    required: false
  get-contributions-fn:
    description: "Check documentation"
    required: false
runs:
  using: composite
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Install npm packages and build code
      run: cd "${{ github.action_path }}" && npm install && npm run build
      shell: bash
    - name: Validate paths
      run: |
        cd "$GITHUB_WORKSPACE"
        for i in "${{ inputs.output-file-path }}" "${{ inputs.file-before-path }}" "${{ inputs.file-after-path }}"; do
          node scripts/checkSafePath.js "$(pwd)" "$i"
        done
      shell: bash
    - name: Run
      run: cd "${{ github.action_path }}" && npm start --silent > "$OUTPUT_FILE_PATH"
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        USERNAME: ${{ github.repository_owner }}
        HEADER_FORMAT: ${{ inputs.header-format }}
        HIGHLIGHT_FORMAT: ${{ inputs.highlight-format }}
        FILE_BEFORE_PATH: ${{ github.workspace }}/${{ inputs.file-before-path }}
        FILE_AFTER_PATH: ${{ github.workspace }}/${{ inputs.file-after-path }}
        OUTPUT_FILE_PATH: ${{ github.workspace }}/${{ inputs.output-file-path }}
        MINIMUM_STARS_FOR_HIGHLIGHT: ${{ inputs.minimum-stars-for-highlight }}
        MONTHS_INTERVAL: ${{ inputs.months-interval }}
        GET_CONTRIBUTIONS_FN: ${{ inputs.get-contributions-fn }}
    - name: Commit
      run: |
        cd "$GITHUB_WORKSPACE"
        if [[ `git status --porcelain` ]]; then
          git add -A
          git config --global user.email "contributions-getter"
          git config --global user.name "contributions-getter"
          git commit -m "Update contributions"
          git push
        else
          echo "No changes"
        fi
      shell: bash
