name: contributions-getter-actions
description: "Update a markdown file with all of the repositories you have contributed to since your account creation"
inputs:
  token:
    description: "Your GitHub token"
    required: true
  username:
    description: "Your GitHub username"
    required: false
    default: ${{ github.repository_owner }}
  output-file-path:
    description: "The name of the file in which to output the contributions"
    required: false
    default: "README.md"
  header-format:
    description: "Check documentation"
    required: false
  highlight-format:
    description: "Check documentation"
    required: false
  file-before-path:
    description: "Check documentation"
    required: false
  file-after-path:
    description: "Check documentation"
    required: false
  minimum-stars-for-highlight:
    description: "Check documentation"
    required: false
  months-interval:
    description: "Check documentation"
    required: false
  get-contributions-fn:
    description: "Check documentation"
    required: false
runs:
  using: composite
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Install npm packages and build code
      run: cd "${{ github.action_path }}" && npm install && npm run build
      shell: bash
    - name: Validate paths
      run: |
        cd "$GITHUB_WORKSPACE"
        for i in "${{ inputs.output-file-path }}" "${{ inputs.file-before-path }}" "${{ inputs.file-after-path }}"; do
          node scripts/checkSafePath.js "$(pwd)" "$i"
        done
      shell: bash
    - name: Set env vars
      run: |
        names=("TOKEN" "USERNAME" "HEADER_FORMAT" "HIGHLIGHT_FORMAT" "FILE_BEFORE_PATH" "FILE_AFTER_PATH" \
        "MINIMUM_STARS_FOR_HIGHLIGHT" "MONTHS_INTERVAL" "GET_CONTRIBUTIONS_FN" "OUTPUT_FILE_PATH")

        values=("${{ inputs.token }}" "${{ github.repository_owner }}" "${{ inputs.header-format }}" \
        "${{ inputs.highlight-format }}" "${{ inputs.file-before-path }}" "${{ inputs.file-after-path }}" \
        "${{ inputs.minimum-stars-for-highlight }}" "${{ inputs.months-interval }}" \
        "${{ inputs.get-contributions-fn }}" ${{ inputs.output-file-path }})

        length=${#names[@]}
        let l=$length-1
        for i in $(seq 0 $l); do
          if [ -n "${values[i]}" ]; then
            if [[ ${names[i]} = *_PATH ]]; then
              values[$i]="$GITHUB_WORKSPACE/${values[i]}"
            fi
            echo "${names[i]}=${values[i]}" >> "$GITHUB_ENV"
          fi
        done
      shell: bash
    - name: Run
      run: cd "${{ github.action_path }}" && npm start --silent > "$OUTPUT_FILE_PATH"
      shell: bash
    - name: Commit
      run: |
        cd "$GITHUB_WORKSPACE"
        if [[ `git status --porcelain` ]]; then
          git add -A
          git config --global user.email "contributions-getter"
          git config --global user.name "contributions-getter"
          git commit -m "Update contributions"
          git push
        else
          echo "No changes"
        fi
      shell: bash
