name: contributions-getter-actions
description: "Update a markdown file with all of the repositories you have contributed to since your account creation"
inputs:
  token:
    description: Your GitHub token
    required: true
  username:
    description: Your GitHub username
    required: false
    default: ${{ github.repository_owner }}
  output-file-path:
    description: The name of the file in which to output the contributions
    required: false
    default: README.md
  header-format:
    description: Check documentation
    required: false
  highlight-format:
    description: Check documentation
    required: false
  file-before-path:
    description: Check documentation
    required: false
  file-after-path:
    description: Check documentation
    required: false
  minimum-stars-for-highlight:
    description: Check documentation
    required: false
  months-interval:
    description: Check documentation
    required: false
  mock-get-contributions-fn:
    description: Check documentation
    required: false
  sort-repos-fn:
    description: Check documentation
    required: false
  repos-to-ignore:
    description: Check documentation
    required: false
runs:
  using: composite
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Validate paths
      run: |
        cd "$GITHUB_WORKSPACE"
        for i in '${{ inputs.output-file-path }}' '${{ inputs.file-before-path }}' '${{ inputs.file-after-path }}'; do
          node scripts/checkSafePath.js "$(pwd)" "$i" || exit 1
        done
      shell: bash
    - name: Install npm packages and build code
      run: cd '${{ github.action_path }}' && npm ci && npm run build
      shell: bash
    - name: Set env vars and run
      run: |
        cd "$GITHUB_WORKSPACE"
        for i in 'TOKEN=${{ inputs.token }}' 'USERNAME=${{ inputs.username }}' \
        'HEADER_FORMAT=${{ inputs.header-format }}' 'HIGHLIGHT_FORMAT=${{ inputs.highlight-format }}' \
        'FILE_BEFORE_PATH=${{ inputs.file-before-path }}' 'FILE_AFTER_PATH=${{ inputs.file-after-path }}' \
        'MINIMUM_STARS_FOR_HIGHLIGHT=${{ inputs.minimum-stars-for-highlight }}' \
        'MONTHS_INTERVAL=${{ inputs.months-interval }}' \
        'MOCK_GET_CONTRIBUTIONS_FN=${{ inputs.mock-get-contributions-fn }}' \
        'OUTPUT_FILE_PATH=${{ inputs.output-file-path }}' 'SORT_REPOS_FN=${{ inputs.sort-repos-fn }}' \
        'REPOS_TO_IGNORE=${{ inputs.repos-to-ignore }}'; do
          key="$(node scripts/splitString.js $i '=' 0)"
          value="$(node scripts/splitString.js $i '=' 1)"
          if [ -n "$value" ]; then
            if [[ $key = *_PATH ]]; then
              value="$GITHUB_WORKSPACE/$value"
            fi
            declare -gx "$key=$value"
          else
            unset "$key"
          fi
        done
        cd '${{ github.action_path }}' && npm start --silent > "$OUTPUT_FILE_PATH"
      shell: bash
    - name: Commit
      run: |
        cd "$GITHUB_WORKSPACE"
        if [[ `git status --porcelain` ]]; then
          git add -A
          git config --global user.email "contributions-getter"
          git config --global user.name "contributions-getter"
          git commit -m "Update contributions"
          git push
        else
          echo "No changes"
        fi
      shell: bash
