name: contributions-getter-actions
author: Omar Brikaa
description: |
  Update a markdown file with all of the repositories a user has contributed to since their account's creation.
branding:
  icon: user-check
  color: green
inputs:
  token:
    description: Your GitHub token
    required: true
  username:
    description: Your GitHub username
    required: false
    default: ${{ github.repository_owner }}
  output-file-path:
    description: The name of the file in which to output the contributions
    required: false
    default: README.md
  header-format:
    description: the format of the repository header
    required: false
  highlight-format:
    description: the format of highlighted repositories (repositories having a certain number of stars)
    required: false
  file-before-path:
    description: the path of the file containing the content to put before the contributions (relative to the repo)
    required: false
  file-after-path:
    description: the path of the file containing the content to put after the contributions (relative to the repo)
    required: false
  minimum-stars-for-highlight:
    description: the minimum stars required for a repository to be highlighted
    required: false
  months-interval:
    description: the interval in which to get the contributions
    required: false
  mock-get-contributions-fn:
    description: use this if you want to test with a mock function (can be one of "SINGLE", "EMPTY" or "MULTIPLE")
    required: false
  sort-repos-fn:
    description: how to sort the repos in each contribution interval (can be one of "STARS" or "COMMITS")
    required: false
  repos-to-ignore:
    description: comma separated list of repos to ignore
    required: false
runs:
  using: composite
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Validate paths
      run: |
        cd "$GITHUB_ACTION_PATH"
        for i in "$OUTPUT_FILE_PATH" "$FILE_BEFORE_PATH" "$FILE_AFTER_PATH"; do
          node scripts/checkSafePath.js "$(pwd)" "$i" || exit 1
        done
      shell: bash
      env:
        OUTPUT_FILE_PATH: ${{ inputs.output-file-path }}
        FILE_BEFORE_PATH: ${{ inputs.file-before-path }}
        FILE_AFTER_PATH: ${{ inputs.file-after-path }}
    - name: Install npm packages and build code
      run: cd "$GITHUB_ACTION_PATH" && npm ci && npm run build
      shell: bash
    - name: Set env vars and run
      run: |
        cd "$GITHUB_ACTION_PATH"
        l=$(node scripts/inputsToDeclarations.js "$INPUTS")
        for i in $(seq 1 $l); do
          declaration=$(node scripts/inputsToDeclarations.js "$INPUTS" "$i")
          key="$(node scripts/splitString.js $declaration '=' 1)"
          value="$(node scripts/splitString.js $declaration '=' 2)"
          if [ -n "$value" ]; then
            if [[ $key = *_PATH ]]; then
              value="$GITHUB_WORKSPACE/$value"
            fi
            declare -gx "$key=$value"
          else
            unset "$key"
          fi
        done
        npm start --silent > "$OUTPUT_FILE_PATH"
      shell: bash
      env:
        INPUTS: ${{ toJson(inputs) }}
    - name: Commit
      run: |
        cd "$GITHUB_WORKSPACE"
        if [[ `git status --porcelain` ]]; then
          git add -A
          git config --global user.email "contributions-getter"
          git config --global user.name "contributions-getter"
          git commit -m "Update contributions"
          git push
        else
          echo "No changes"
        fi
      shell: bash
