name: contributions-getter
on: workflow_dispatch
jobs:
  contributions_getter_job:
    runs-on: ubuntu-latest
    name: contributions-getter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install npm packages and build code
        run: npm install && npm run build
        shell: bash
      - name: Run unit tests
        run: npm test
        shell: bash
      - name: Set env vars
        run: |
          cat tests/main/outputs/.env >> $GITHUB_ENV
          echo "TESTS_RESULT=$(cat tests/main/outputs/unit.md)" >> $GITHUB_ENV
        shell: bash
      - name: Set happy path output
        uses: ./
        with:
          token: ${{ env.TOKEN }}
          username: ${{ env.USERNAME }}
          output-file-path: tests/main/outputs/action.md
          header-format: ${{ env.HEADER_FORMAT }}
          highlight-format: ${{ env.HIGHLIGHT_FORMAT }}
          file-before-path: ${{ env.FILE_BEFORE_PATH }}
          file-after-path: ${{ env.FILE_AFTER_PATH }}
          minimum-stars-for-highlight: ${{ env.MINIMUM_STARS_FOR_HIGHLIGHT }}
          months-interval: ${{ env.MONTHS_INTERVAL }}
          get-contributions-fn: ${{ env.GET_CONTRIBUTIONS_FN }}
      - name: Verify happy path output
        run: |
          echo $TESTS_RESULT > tests/main/outputs/unit.md
          cat tests/main/outputs/unit.md
          cmp tests/main/outputs/unit.md tests/main/outputs/action.md && echo "Got same output as unit tests" \
          || echo "Got different output than unit tests" && exit 1
        shell: bash
