name: contributions-getter
on: workflow_dispatch
jobs:
  contributions_getter_job:
    runs-on: ubuntu-latest
    name: contributions-getter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install npm packages and build code
        run: npm install && npm run build
        shell: bash
      - name: Run unit tests
        run: npm test
        shell: bash
      - name: Set env vars
        run: cat tests/main/outputs/.env >> $GITHUB_ENV
        shell: bash
      - name: Set normal path output
        uses: ./
        with:
          token: ${{ env.TOKEN }}
          username: ${{ env.USERNAME }}
          output-file-name: ${{ env.GITHUB_WORKSPACE }}/action.md
          header-format: ${{ env.HEADER_FORMAT }}
          highlight-format: ${{ env.HIGHLIGHT_FORMAT }}
          file-before-path: ${{ env.FILE_BEFORE_PATH }}
          file-after-path: ${{ env.FILE_AFTER_PATH }}
          minimum-stars-for-highlight: ${{ env.MINIMUM_STARS_FOR_HIGHLIGHT }}
          months-interval: ${{ env.MONTHS_INTERVAL }}
          get-contributions-fn: ${{ env.GET_CONTRIBUTIONS_FN }}
      - name: verify normal path output
        run: |
          if [[ `cmp "$GITHUB_WORKSPACE/action.md" tests/main/outputs/unit.md` ]]; then
            echo "Got same output as unit tests"
          else
            echo "Got different outputs than unit tests"
            exit 1
          fi
