name: contributions-getter
on: workflow_dispatch
jobs:
  contributions_getter_job:
    runs-on: ubuntu-latest
    name: contributions-getter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: contributions-getter-actions-main
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install npm packages and build code
        run: cd "$GITHUB_WORKSPACE/contributions-getter-actions-main" && npm install && npm run build
        shell: bash
      - name: Run unit tests
        run: cd "$GITHUB_WORKSPACE/contributions-getter-actions-main" && npm test
        shell: bash
      - name: Set env vars
        run: cat "$GITHUB_WORKSPACE/contributions-getter-actions-main/tests/main/outputs/.env" >> $GITHUB_ENV
        shell: bash
      - name: Set normal path output
        uses: ${{ env.GITHUB_WORKSPACE }}/contributions-getter-actions-main
        with:
          token: ${{ env.TOKEN }}
          username: ${{ env.USERNAME }}
          output-file-path: tests/main/outputs/action.md
          header-format: ${{ env.HEADER_FORMAT }}
          highlight-format: ${{ env.HIGHLIGHT_FORMAT }}
          file-before-path: ${{ env.FILE_BEFORE_PATH }}
          file-after-path: ${{ env.FILE_AFTER_PATH }}
          minimum-stars-for-highlight: ${{ env.MINIMUM_STARS_FOR_HIGHLIGHT }}
          months-interval: ${{ env.MONTHS_INTERVAL }}
          get-contributions-fn: ${{ env.GET_CONTRIBUTIONS_FN }}
      - name: verify normal path output
        run: |
          if [[ `cmp "$GITHUB_WORKSPACE/contributions-getter-actions/tests/main/outputs/action.md" \
          "$GITHUB_WORKSPACE/contributions-getter-actions-main/tests/main/outputs/unit.md"` ]]; then
            echo "Got same output as unit tests"
          else
            echo "Got different output than unit tests"
            exit 1
          fi
        shell: bash
